definitions:
  azure.Fields:
    properties:
      System.Reason:
        type: string
      System.Title:
        type: string
      System.WorkItemType:
        type: string
    type: object
  azure.WorkItem:
    properties:
      fields:
        $ref: '#/definitions/azure.Fields'
        type: object
      id:
        type: integer
      rev:
        type: integer
      url:
        type: string
    type: object
  azure.WorkItemsResponse:
    properties:
      count:
        type: integer
      value:
        items:
          $ref: '#/definitions/azure.WorkItem'
        type: array
    type: object
  httputil.HTTPError:
    properties:
      message:
        example: status bad request
        type: string
      status_code:
        example: 400
        type: integer
    type: object
  models.Iteration:
    properties:
      finishDate:
        type: string
      id:
        type: string
      name:
        type: string
      path:
        type: string
      startDate:
        type: string
      timeFrame:
        type: string
    type: object
  models.Member:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  models.Project:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  models.Team:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  description: Created by mobile developers
  license: {}
  title: Databriz Meetings Api
  version: "0.1"
paths:
  /api/v1/azure/getMemberWorkItems/{projectId}/{teamId}:
    get:
      parameters:
      - description: Project Id
        in: path
        name: projectId
        required: true
        type: string
      - description: Team Id
        in: path
        name: teamId
        required: true
        type: string
      - description: User Email
        in: query
        name: userEmail
        required: true
        type: string
      - description: Iteration Name
        in: query
        name: iteration
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/azure.WorkItemsResponse'
        "400":
          description: When user has not provided projectId or teamId parameter
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: When failed to receive data from Azure
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Задачи определенного участника команды
      tags:
      - Azure
  /api/v1/azure/getProjectTeams/{projectId}:
    get:
      description: Возвращает список команд проекта
      parameters:
      - description: Project Id
        in: path
        name: projectId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Team'
            type: array
        "400":
          description: When user has not provided projectId parameter
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: When failed to receive data from Azure
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Список команд
      tags:
      - Azure
  /api/v1/azure/getProjects:
    get:
      description: Возвращает список проектов организации
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Project'
            type: array
        "500":
          description: When failed to receive data from Azure
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Список проектов
      tags:
      - Azure
  /api/v1/azure/getTeamIterations/{projectId}/{teamId}:
    get:
      description: Возвращает список спринтов команды
      parameters:
      - description: Project Id
        in: path
        name: projectId
        required: true
        type: string
      - description: Team Id
        in: path
        name: teamId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Iteration'
            type: array
        "400":
          description: When user has not provided projectId or teamId parameter
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: When failed to receive data from Azure
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Список спринтов команды
      tags:
      - Azure
  /api/v1/azure/getTeamMembers/{projectId}/{teamId}:
    get:
      description: Возвращает список участников команды проекта
      parameters:
      - description: Project Id
        in: path
        name: projectId
        required: true
        type: string
      - description: Team Id
        in: path
        name: teamId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Member'
            type: array
        "400":
          description: When user has not provided projectId or teamId parameter
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: When failed to receive data from Azure
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Список участников команды
      tags:
      - Azure
swagger: "2.0"
